Adding git workflows with test matrix and common workflows
awslabs/deequ pull request #363
Opened 2021-05-10 21:39 UTC by ChethanUK

1. Adding GitHub workflows to test across various matrix while merging PR or pushing to master or even before releasing new version

```bash
          - java: 8
            hadoop: 2.7
            spark-version: 2.4.7
          - java: 8
            hadoop: 3.2
            spark-version: 3.0.2
          - java: 11
            hadoop: 3.2
            spark-version: 3.0.2
          - java: 8
            hadoop: 2.7
            spark-version: 3.0.2
          - java: 11
            hadoop: 2.7
            spark-version: 3.0.2
          - java: 8
            hadoop: 3.2
            spark-version: 3.1.1
          - java: 11
            hadoop: 3.2
            spark-version: 3.1.1
          - java: 8
            hadoop: 2.7
            spark-version: 3.1.1
          - java: 11
            hadoop: 2.7
            spark-version: 3.1.1
```

2. Adding workflows for some common git workflows (Github action to mark as stale and close issues) etc.

cc: @twollnik @TammoR

2021-05-12 15:42 UTC, twollnik commented
Hi, Thanks for introducing these changes! We will have a look within the next two weeks.

2021-05-19 17:36 UTC, ChethanUK commented
> Hi, Thanks for introducing these changes! We will have a look within the next two weeks.

Sure, I will update it. There are few changes, will push it in weekend [when I get some time]

2021-05-23 15:48 UTC, ChethanUK commented
@twollnik Also, When will be Spark 3.1.1 supported by deequ?

2021-05-24 04:06 UTC, aviatesk commented
see #366

2021-06-08 15:33 UTC, twollnik requested changes
This looks super useful overall, thanks! We would like to add just the testing workflow for now to keep the scope of the PR small (and to be honest because we are no github experts and don't feel comfortable maintaining a lot of github config code).  Thanks!

2021-06-10 06:53 UTC, ChethanUK commented on .github/workflows/build_test.yml
> +        python-version: [3.7, 3.8]
Internally I had mono repo both deequ and python-deequ, I will remove it

2021-06-10 06:54 UTC, ChethanUK commented on .github/workflows/build_test.yml
> +        python-version: [3.7, 3.8]
On Side note, Having one mono repo for both is better

2021-06-10 11:56 UTC, twollnik commented
Thanks so much for your quick reaction on this and for making changes. It will likely take some time for us to react to the updated PR, but we will get around to it!

2021-06-21 15:05 UTC, chethanu commented
@twollnik Any update? and Also waiting for Spark 3.1 support as well.

2021-06-21 15:11 UTC, ChethanUK commented
@twollnik Any update? and Also waiting for Spark 3.1 support as well.

2021-07-13 16:00 UTC, ChethanUK commented
Ping!.

2021-07-20 14:33 UTC, twollnik commented
Thanks for your patience on this. 

@sscdotopen could you please take a look and let us know what you think about the proposed changes?

2026-05-09 13:57 UTC, chethanuk commented
Is Project still active?

2026-05-18 19:17 UTC, sudsali commented
@chethanuk yes the project is definitely active! 
Thanks for proposing this tho! We've since added our own CI/CD workflows (bot review, auto-approve, stale management, knowledge base updates) that cover these use cases. Closing as superseded.

2026-05-18 19:17 UTC, closed without merging